<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-MNVGOOD" failures="2" tests="2" name="group test" time="19.155" errors="0" timestamp="2023-07-17T08:56:02 MDT">
  <testcase classname="testCases.TC_001_AccountRegistrationTest" name="test_Acc_Registration" time="2.283">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at testCases.TC_001_AccountRegistrationTest.test_Acc_Registration(TC_001_AccountRegistrationTest.java:47)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- test_Acc_Registration -->
  <testcase classname="testCases.TC_002_LoginTest" name="test_AccountLogin" time="10.769">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Login not successfull expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Login not successfull expected [true] but found [false]
at testCases.TC_002_LoginTest.test_AccountLogin(TC_002_LoginTest.java:36)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- test_AccountLogin -->
</testsuite> <!-- group test -->
